Softfail by default
Use softfail setting for importing remote packages.  This resolves issues such as

fatal error: Can't find overlay named NaOH.link in [:]: file atpkg/src/Package.swift, line 375

(when it is not required as it's a test-only dependency)